### PR TITLE
Add netid validation

### PR DESCRIPTION
**Pull request by sameetandpotatoes**
I added some stricter netid validation so that we specifically look for 2-8 lowercase characters, then between 1-4 digits between 0-9. Anything that doesn't match this pattern will return a bad request.

Addresses https://github.com/acm-uiuc/groot-desktop-frontend/issues/121

### CODE REVIEW

**Comment by bcongdon** [comment]
NP: Isn't the maximum number of characters in a netid 8? This regex will still match `abcdefgh1234`

**Comment by sameetandpotatoes** [comment]
Yeah it is. I updated it a bit to also look for a length greater than 8. Tested it via the UI's join form.

**Comment by narendasan** [comment]
Can you write unit tests for this component? Seems pretty modular and something we would want to explicitly test

**Comment by sameetandpotatoes** [comment]
@narendasan unit tests added

**Comment by narendasan** [comment]
lgtm, small thing I would look to add in an new pr is to make a rake task that runs rubocop and rspec so devs can test easier (also a single command to call in the travis.ci)

**Pull request merged**
