### PR TITLE
Changes Netid Validation Regex for Edge case

### PR DESCRIPTION
**Pull request by aashishkapur**

### CODE REVIEW

**Comment by apache8080** [comment]
@aashishkapur lgtm, can you check why the CI checks are failing

**Comment by aashishkapur** [comment]
It’s because there were changes to the style guidelines. I’d like to merge this PR and fix the changes on a second PR, if you’re good with that(and @bcongdon).

**Comment by bcongdon** [comment]
Fine by me either way.

**Comment by sujaypat** [comment]
Rebased this branch, please re-review

**Pull request merged**
